name: assignment2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - nbconvert
  - r-base
  - r-ggplot2
  - r-irkernel
